//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string SFName { get; set; }
        public string SSName { get; set; }
        public string SLName { get; set; }
        public int StockId { get; set; }
        public string Password { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
