//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Inventory.Model
{
    using System;
    using System.Collections.Generic;
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.InProducts = new HashSet<InProduct>();
            this.OutProducts = new HashSet<OutProduct>();
        }
        public int ProductId { get; set; }
        public string PName { get; set; }
        public string PGroup { get; set; }
        public string PUnit { get; set; }
        public string PCountry { get; set; }
        public int ProducerId { get; set; }
        public Nullable<int> nost { get; set; }
        public Nullable<int> rost { get; set; }
        public Nullable<int> dif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InProduct> InProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutProduct> OutProducts { get; set; }
        public virtual Producer Producer { get; set; }
    }
}
